# MUDANÇA 1: Usamos a imagem completa (não-alpine) para evitar falta de bibliotecas do sistema
FROM node:22 as build

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./

# MUDANÇA 2: Instalação forçada para ignorar conflitos de dependência
RUN npm install --legacy-peer-deps

# Copia todo o código fonte
COPY . .

# MUDANÇA 3: Desativa coleta de dados do Angular que às vezes trava o build
ENV NG_CLI_ANALYTICS=ci

# MUDANÇA 4: Garante memória máxima para o Node (4GB)
ENV NODE_OPTIONS="--max-old-space-size=4096"

# Executa o build
RUN npm run build

# --- Etapa 2: Servidor Nginx (Mantida igual) ---
FROM nginx:alpine
COPY --from=build /app/dist/frontend-rede-social/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80