# Etapa 1: Build do Angular
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Gera a pasta dist
RUN npm run build

# Etapa 2: Servidor Nginx
FROM nginx:alpine
# Copia o build do Angular para o Nginx
# ATENÇÃO: Verifique se o nome da pasta no seu dist é 'frontend-rede-social'
COPY --from=build /app/dist/frontend-rede-social/browser /usr/share/nginx/html

# Configuração para o Nginx não dar erro 404 ao recarregar página
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80