# Usa uma imagem leve do Node
FROM node:22 as build

# Cria a pasta dentro do container
WORKDIR /app

# Copia os arquivos de dependências
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o resto do código
COPY . .

# Expõe a porta 3000
EXPOSE 3000

# Comando para rodar
CMD ["node", "index.js"]